# Generated by Django 3.2.5 on 2021-07-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EN_word', models.TextField(blank=True, null=True)),
                ('KO_word', models.TextField(blank=True, null=True)),
                ('memorize', models.CharField(blank=True, max_length=50, null=True)),
                ('Class', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
