# Generated by Django 3.2.5 on 2021-07-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='user',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
