# Generated by Django 3.2.5 on 2021-08-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_auto_20210713_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='dt_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='dt_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='user',
            field=models.CharField(blank=True, max_length=99999999999999, null=True),
        ),
    ]
