# Generated by Django 3.2.5 on 2021-10-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_auto_20210803_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='trainingSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('explanation', models.CharField(blank=True, max_length=600, null=True)),
            ],
        ),
    ]
