# Generated by Django 3.2.5 on 2021-10-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0005_trainingset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='memorize',
        ),
        migrations.RemoveField(
            model_name='word',
            name='user',
        ),
        migrations.AddField(
            model_name='trainingset',
            name='user',
            field=models.CharField(blank=True, max_length=99999999999999, null=True),
        ),
    ]
