# Generated by Django 3.2.5 on 2021-10-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0007_auto_20211011_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingset',
            name='words_length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
