# Generated by Django 3.2.5 on 2021-10-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0008_trainingset_words_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingset',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
